sonar.projectKey=NBUSW_NVMesh_NVMesh_interop-db
sonar.qualitygate.wait=true
sonar.host.url=https://sonar.nvidia.com/

sonar.sources=.
sonar.coverage.exclusions=
sonar.exclusions=**/*.sql
sonar.test.inclusions=
